### PR TITLE
Test PR

### PR DESCRIPTION
**Pull request by maleadt**

### CODE REVIEW

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
[Your job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375344474) failed. cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
[Your job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375345768) failed. cc @maleadt

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375346867) has completed - no new issues were detected. A full report can be found [here](https://github.com/maleadt/NanosoldierReports/blob/master/pkgeval/by_hash/be00706_vs_8f009b2/report.md).

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
[Your package evaluation job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375351759) has completed - no new issues were detected. A full report can be found [here](https://github.com/maleadt/NanosoldierReports/blob/master/pkgeval/by_hash/be00706_vs_8f009b2/report.md).

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by nanosoldier** [comment]
Invalid job submission.

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob maleadt/Adapt.jl@be00706 vs. maleadt/Adapt.jl@8f009b2: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob maleadt/Adapt.jl@be00706 vs. maleadt/Adapt.jl@8f009b2: Running

**Comment by maleadt** [comment]
@nanosoldier `runtests(["GPUArraysCore"])`

**Comment by nanosoldier** [comment]
Update on PkgEvalJob maleadt/Adapt.jl@be00706 vs. maleadt/Adapt.jl@8f009b2: Accepted

**Comment by nanosoldier** [comment]
Update on PkgEvalJob maleadt/Adapt.jl@be00706 vs. maleadt/Adapt.jl@8f009b2: Running

**Comment by nanosoldier** [comment]
[Your package evaluation job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375578753) has completed - no new issues were detected.
A full report can be found [here](https://github.com/maleadt/NanosoldierReports/blob/master/pkgeval/by_hash/be00706_vs_8f009b2/report.md).

**Comment by maleadt** [comment]
@nanosoldier `runtests(foobar)`

**Comment by nanosoldier** [comment]
Invalid job submission.

**Comment by maleadt** [comment]
@nanosoldier `runtests(foobar)`

**Comment by maleadt** [comment]
@nanosoldier `runtests(foobar)`

**Comment by nanosoldier** [comment]
[Your job](https://github.com/maleadt/Adapt.jl/pull/1#issuecomment-1375689882) was not accepted, please verify the trigger phrase syntax.

**Pull request closed without merging**
